/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelegramBotsRouteImport } from './routes/telegram-bots'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvitoRouteImport } from './routes/avito'
import { Route as AiWebsitesRouteImport } from './routes/ai-websites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiDebugTelegramPingRouteImport } from './routes/api/debug/telegram-ping'

const TelegramBotsRoute = TelegramBotsRouteImport.update({
  id: '/telegram-bots',
  path: '/telegram-bots',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvitoRoute = AvitoRouteImport.update({
  id: '/avito',
  path: '/avito',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWebsitesRoute = AiWebsitesRouteImport.update({
  id: '/ai-websites',
  path: '/ai-websites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugTelegramPingRoute = ApiDebugTelegramPingRouteImport.update({
  id: '/api/debug/telegram-ping',
  path: '/api/debug/telegram-ping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-websites': typeof AiWebsitesRoute
  '/avito': typeof AvitoRoute
  '/blog': typeof BlogRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telegram-bots': typeof TelegramBotsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/debug/telegram-ping': typeof ApiDebugTelegramPingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-websites': typeof AiWebsitesRoute
  '/avito': typeof AvitoRoute
  '/blog': typeof BlogRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telegram-bots': typeof TelegramBotsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/debug/telegram-ping': typeof ApiDebugTelegramPingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-websites': typeof AiWebsitesRoute
  '/avito': typeof AvitoRoute
  '/blog': typeof BlogRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telegram-bots': typeof TelegramBotsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/debug/telegram-ping': typeof ApiDebugTelegramPingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-websites'
    | '/avito'
    | '/blog'
    | '/cases'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/telegram-bots'
    | '/api/chat'
    | '/api/lead'
    | '/api/debug/telegram-ping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-websites'
    | '/avito'
    | '/blog'
    | '/cases'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/telegram-bots'
    | '/api/chat'
    | '/api/lead'
    | '/api/debug/telegram-ping'
  id:
    | '__root__'
    | '/'
    | '/ai-websites'
    | '/avito'
    | '/blog'
    | '/cases'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/telegram-bots'
    | '/api/chat'
    | '/api/lead'
    | '/api/debug/telegram-ping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiWebsitesRoute: typeof AiWebsitesRoute
  AvitoRoute: typeof AvitoRoute
  BlogRoute: typeof BlogRoute
  CasesRoute: typeof CasesRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TelegramBotsRoute: typeof TelegramBotsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiLeadRoute: typeof ApiLeadRoute
  ApiDebugTelegramPingRoute: typeof ApiDebugTelegramPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telegram-bots': {
      id: '/telegram-bots'
      path: '/telegram-bots'
      fullPath: '/telegram-bots'
      preLoaderRoute: typeof TelegramBotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avito': {
      id: '/avito'
      path: '/avito'
      fullPath: '/avito'
      preLoaderRoute: typeof AvitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-websites': {
      id: '/ai-websites'
      path: '/ai-websites'
      fullPath: '/ai-websites'
      preLoaderRoute: typeof AiWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/telegram-ping': {
      id: '/api/debug/telegram-ping'
      path: '/api/debug/telegram-ping'
      fullPath: '/api/debug/telegram-ping'
      preLoaderRoute: typeof ApiDebugTelegramPingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiWebsitesRoute: AiWebsitesRoute,
  AvitoRoute: AvitoRoute,
  BlogRoute: BlogRoute,
  CasesRoute: CasesRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TelegramBotsRoute: TelegramBotsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiLeadRoute: ApiLeadRoute,
  ApiDebugTelegramPingRoute: ApiDebugTelegramPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
