/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TgRouteImport } from './routes/tg'
import { Route as TelegramBotsRouteImport } from './routes/telegram-bots'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AvitoRouteImport } from './routes/avito'
import { Route as AiWebsitesRouteImport } from './routes/ai-websites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiDebugTelegramPingRouteImport } from './routes/api/debug/telegram-ping'

const TgRoute = TgRouteImport.update({
  id: '/tg',
  path: '/tg',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramBotsRoute = TelegramBotsRouteImport.update({
  id: '/telegram-bots',
  path: '/telegram-bots',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AvitoRoute = AvitoRouteImport.update({
  id: '/avito',
  path: '/avito',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWebsitesRoute = AiWebsitesRouteImport.update({
  id: '/ai-websites',
  path: '/ai-websites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugTelegramPingRoute = ApiDebugTelegramPingRouteImport.update({
  id: '/api/debug/telegram-ping',
  path: '/api/debug/telegram-ping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-websites': typeof AiWebsitesRoute
  '/avito': typeof AvitoRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/geo': typeof GeoRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telegram-bots': typeof TelegramBotsRoute
  '/tg': typeof TgRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/debug/telegram-ping': typeof ApiDebugTelegramPingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-websites': typeof AiWebsitesRoute
  '/avito': typeof AvitoRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/geo': typeof GeoRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telegram-bots': typeof TelegramBotsRoute
  '/tg': typeof TgRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/debug/telegram-ping': typeof ApiDebugTelegramPingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-websites': typeof AiWebsitesRoute
  '/avito': typeof AvitoRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/geo': typeof GeoRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telegram-bots': typeof TelegramBotsRoute
  '/tg': typeof TgRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/debug/telegram-ping': typeof ApiDebugTelegramPingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-websites'
    | '/avito'
    | '/cases'
    | '/contact'
    | '/crm'
    | '/geo'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/telegram-bots'
    | '/tg'
    | '/api/chat'
    | '/api/lead'
    | '/blog/$slug'
    | '/blog/'
    | '/api/debug/telegram-ping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-websites'
    | '/avito'
    | '/cases'
    | '/contact'
    | '/crm'
    | '/geo'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/telegram-bots'
    | '/tg'
    | '/api/chat'
    | '/api/lead'
    | '/blog/$slug'
    | '/blog'
    | '/api/debug/telegram-ping'
  id:
    | '__root__'
    | '/'
    | '/ai-websites'
    | '/avito'
    | '/cases'
    | '/contact'
    | '/crm'
    | '/geo'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/telegram-bots'
    | '/tg'
    | '/api/chat'
    | '/api/lead'
    | '/blog/$slug'
    | '/blog/'
    | '/api/debug/telegram-ping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiWebsitesRoute: typeof AiWebsitesRoute
  AvitoRoute: typeof AvitoRoute
  CasesRoute: typeof CasesRoute
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRoute
  GeoRoute: typeof GeoRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TelegramBotsRoute: typeof TelegramBotsRoute
  TgRoute: typeof TgRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiLeadRoute: typeof ApiLeadRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiDebugTelegramPingRoute: typeof ApiDebugTelegramPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tg': {
      id: '/tg'
      path: '/tg'
      fullPath: '/tg'
      preLoaderRoute: typeof TgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram-bots': {
      id: '/telegram-bots'
      path: '/telegram-bots'
      fullPath: '/telegram-bots'
      preLoaderRoute: typeof TelegramBotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avito': {
      id: '/avito'
      path: '/avito'
      fullPath: '/avito'
      preLoaderRoute: typeof AvitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-websites': {
      id: '/ai-websites'
      path: '/ai-websites'
      fullPath: '/ai-websites'
      preLoaderRoute: typeof AiWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/telegram-ping': {
      id: '/api/debug/telegram-ping'
      path: '/api/debug/telegram-ping'
      fullPath: '/api/debug/telegram-ping'
      preLoaderRoute: typeof ApiDebugTelegramPingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiWebsitesRoute: AiWebsitesRoute,
  AvitoRoute: AvitoRoute,
  CasesRoute: CasesRoute,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRoute,
  GeoRoute: GeoRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TelegramBotsRoute: TelegramBotsRoute,
  TgRoute: TgRoute,
  ApiChatRoute: ApiChatRoute,
  ApiLeadRoute: ApiLeadRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiDebugTelegramPingRoute: ApiDebugTelegramPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
